# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Jakub Krawczyk - Profile Page
email:
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://krawczyk.me/" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
remote_theme: fnyu/jekyll-profile-page@main
plugins:
  - jekyll-feed

# Theme-specific settings
cover_photo:
  url: assets/images/cover.jpg
  alt: "Mountains covered with snow and dark sky in the background"

profile_picture: assets/images/photo.png

author:
  name: "Jakub Krawczyk"
  occupation: "IT Consultant"
  # Location is optional
  location:
    name: "Warsaw, Poland"
    # If you don't provide the link, only text will be printed
    url: "https://maps.app.goo.gl/EfrtUJaV79nAupqY8"

# Workplaces are optional
work:
  - name: "Self-Employed"
    url: "#"

# Projects are optional
projects:
  - name: "This Jekyll theme"
    url: "https://github.com/fnyu/jekyll-profile-page"

# Social media are optional
# You can use any icon from Font Awesome Brands Pack
social:
  - url: "https://github.com/fnyu"
    title: "GitHub Profile Page"
    icon: "fab fa-github"
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
